= Spring Boot Version Endpoints
:toc: left
:idprefix: spring_boot_version_
:sectanchors:
:icons: font
:last-update-label!:

Boot version endpoints allow you to compare `@ConfigurationProperties` metadata between Spring Boot versions.

=== Versions: /springboot/versions

Lists all known versions of Spring Boot.

Example curl request:
include::{generated}/versions/curl-request.adoc[]

Example HTTP request: [small]##link:#{idprefix}versions_springboot_versions[icon:external-link[role="silver"]]##
include::{generated}/versions/http-request.adoc[]

Example HTTP response:
include::{generated}/versions/http-response.adoc[]


=== Version Diffs: /diff/{from}/{to}

Compares two versions of Spring Boot, listing all the changed configuration properties.

Example curl request:
include::{generated}/valid/curl-request.adoc[]

Example HTTP request: [small]##link:#{idprefix}version_diffs_diff_from_to[icon:external-link[role="silver"]]##
include::{generated}/valid/http-request.adoc[]

Example HTTP response:
include::{generated}/valid/http-response.adoc[]

If you send an invalid version you will get a 400:

Example invalid curl request:
include::{generated}/from-invalid/curl-request.adoc[]

Example invalid HTTP request: [small]##link:#{idprefix}version_diffs_diff_from_to[icon:external-link[role="silver"]]##
include::{generated}/from-invalid/http-request.adoc[]

Example invalid HTTP response:
include::{generated}/from-invalid/http-response.adoc[]
